# Generated by Django 4.0 on 2021-12-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PenyewaanAlatPesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='TransaksiPembeliId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='TransaksiJumlah',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='TransaksiTotal',
            field=models.IntegerField(default=0),
        ),
    ]
